services:
  db:
    container_name: hackutdx
    image: postgres
    ports:
      - "5001:5434"
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: bank
    volumes:
      - db-data:/data/postgres

  api:
    build: ./api
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      DEBUG: "false"

volumes:
  db-data:
